{% set name = "ExitWaveReconstruction" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDoberstein/ExitWaveReconstruction/archive/v{{ version }}.tar.gz
  sha256: fcb2f6a41c920807c5395070e03502c46ffcf8e32bb9940b4997f6f0ce1c4db2

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - fftw
    - bzip2
    - zlib
    - libtiff
    - clblas
    - boost-cpp
    - ocl-icd  # [linux]
    - ocl_icd_wrapper_apple  # [osx]
    - clhpp
    - cimg
    - xorg-libx11
  run:
    - clblas
    - xorg-libx11

test:
  files:
    - Example/ParameterFile.param
  commands:
    - Reconstruction

about:
  home: https://github.com/CDoberstein/ExitWaveReconstruction
  license: CDDL-1.0
  license_file: LICENSE.txt
  summary: Exit wave reconstruction from transmission electron microscopy focal series

  description: |
    Exit wave reconstruction from transmission electron microscopy focal series
  doc_url: https://github.com/CDoberstein/ExitWaveReconstruction
  dev_url: https://github.com/CDoberstein/ExitWaveReconstruction

extra:
  recipe-maintainers:
    - din14970
